apiVersion: v1
kind: Namespace
metadata:
  name: kopeio-auth
  labels:
    k8s-addon: authentication.kope.io
    role.kubernetes.io/authentication: "1"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-portal
  namespace: kopeio-auth
  labels:
    k8s-addon: authentication.kope.io
    role.kubernetes.io/authentication: "1"
spec:
  template:
    metadata:
      labels:
        app: auth-portal
    spec:
      containers:
      - name: auth-portal
        image: kopeio/auth-portal:1.0.20170619
        ports:
        - containerPort: 8080
        command:
        - /auth-portal

---

apiVersion: v1
kind: Service
metadata:
  name: auth-portal
  namespace: kopeio-auth
  labels:
    k8s-addon: authentication.kope.io
    role.kubernetes.io/authentication: "1"
spec:
  selector:
    app: auth-portal
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: auth-api
  namespace: kopeio-auth
  labels:
    k8s-addon: authentication.kope.io
    role.kubernetes.io/authentication: "1"
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      containers:
      - name: auth-api
        image: kopeio/auth-api:1.0.20170619
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        command:
        - /auth-api
        - --listen=127.0.0.1:9001
        - --secure-port=9002
        - --server=https://127.0.0.1:9002
        - --insecure-skip-tls-verify
        - --etcd-servers=http://127.0.0.1:4001
        - --v=8
        - --storage-backend=etcd2

---

apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: kopeio-auth
spec:
  selector:
    app: auth-api
  ports:
  - port: 443
    targetPort: 9002

---

apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.auth.kope.io
spec:
  insecureSkipTLSVerify: true
  group: auth.kope.io
  priority: 150
  service:
    name: auth-api
    namespace: kopeio-auth
  version: v1alpha1

---

apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.config.auth.kope.io
spec:
  insecureSkipTLSVerify: true
  group: config.auth.kope.io
  priority: 150
  service:
    name: auth-api
    namespace: kopeio-auth
  version: v1alpha1
